const rem = px => ({ [px]: `${px / 16}rem` });
module.exports = {
  purge: false,
  darkMode: false, // or 'media' or 'class'
  content: [
    './templates/**/*.php',
    './**/*.php',
  ],
  theme: {
    colors: {
      'white': '#ffffff',
      'black': '#000000',
      'primary': '#282A37',
      'secondary': '#4F4F4F',
      'orange': '#F36D45',
      'lightblue': '#E7F1F7',
      'grey': '#DFD6CD',
      'border-gray': '#D6D6D6',
      'd-grey': '#5B5E71',
    },    
    screens: {
      'smd': { max: '640px' },
      'sm': '640px',
      'mdd': { max: '743px' },
      'md': '744px',
      'lgmd': { max: '991px' },
      'lgm': '992px',
      'lgd': { max: '1023px' },
      'lg': '1024px',
      'xld': { max: '1279px' },
      'xl': '1280px',
      '2xld': { max: '1535px' },
      '2xl': '1536px',
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '1.25rem',
        md: '2.5rem',
      }
    },
    fontFamily: {
      'serif': ['Rift', 'sans-serif'],
      'sans': ['Outfit', 'sans-serif'],
      'prod': ['Outfit', 'sans-serif'],
      // 'serifa': ['Poppins', 'sans-serif'],
      // 'sansa': ['Outfit', 'sans-serif'],
      // 'prod': ['Outfit', 'sans-serif'],
    },
    fontSize: {
      ...rem(0),
      ...rem(1),
      ...rem(12),
      ...rem(13),
      ...rem(14),
      ...rem(15),
      ...rem(16),
      ...rem(17),
      ...rem(18),
      ...rem(20),
      ...rem(22),
      ...rem(23),
      ...rem(24),
      ...rem(25),
      ...rem(26),
      ...rem(27),
      ...rem(28),
      ...rem(30),
      ...rem(32),
      ...rem(33),
      ...rem(34),
      ...rem(35),
      ...rem(36),
      ...rem(40),
      ...rem(42),
      ...rem(44),
      ...rem(46),
      ...rem(48),
      ...rem(50),
      ...rem(52),
      ...rem(53),
      ...rem(54),
      ...rem(55),
      ...rem(56),
      ...rem(58),
      ...rem(60),
      ...rem(62),
      ...rem(64),
      ...rem(66),
      ...rem(69),
      ...rem(70),
      ...rem(71),
      ...rem(72),
      ...rem(80),
      ...rem(87),
      ...rem(88),
      ...rem(90),
      ...rem(94),
      ...rem(100),
      ...rem(111),
      ...rem(120),
      ...rem(123),
      ...rem(140),
      ...rem(142),
      ...rem(150),
      ...rem(200),
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
